[project]
name = "zix"
version = "0.2.0"
description = 'Calculate an understandability score for German texts.'
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"

authors = [
  { name = "Statistisches Amt, Kanton Zürich, Team Data", email = "datashop@statistik.zh.ch" },
]

dependencies = [
  "spacy>=3.8.11",
  "textdescriptives>=2.8.2",
  "de-core-news-sm @ https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-3.8.0/de_core_news_sm-3.8.0-py3-none-any.whl",
  "numpy>=2.2.6",
  "pandas>=2.3.3",
  "scikit-learn>=1.7.2",
]

[project.optional-dependencies]
notebooks = [
  "beautifulsoup4>=4.14.3",
  "ipykernel>=7.1.0",
  "ipywidgets>=8.1.8",
  "jupyter>=1.1.1",
  "lxml>=6.0.2",
  "matplotlib>=3.10.8",
  "openai>=2.14.0",
  "pandarallel>=1.6.5",
  "pyarrow>=22.0.0",
  "python-dotenv>=1.2.1",
  "requests>=2.32.5",
  "seaborn>=0.13.2",
  "tqdm>=4.67.1",
]
dev = [
  "pytest>=9.0.2",
]

